// MATH-069 constant-memory terminal verifier for the r=16 tail stream.
//
// Input is generated by 2026_09_11_math069_r16_block_stream_generator.py:
// a sequence of unsigned 128-bit little-endian ordinary integers, one per
// still-unclosed singleton occurrence after the exact 8/16-step handoff.
//
// The verifier uses exact 8-step shortcut blocks.  For each residue mod 256 it
// also records the exact initial-state threshold for reaching <=2^71 at any
// intermediate one of the next eight shortcut steps.  Thus it never skips a
// descent hidden inside a block.
//
// No hash table or duplicate set is needed; memory remains O(1).

#include <algorithm>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <string>

using u128 = unsigned __int128;

static const u128 LO = (u128)1 << 71;

struct Entry {
    unsigned long long A8 = 1;
    unsigned long long C8 = 0;
    unsigned long long A[8]{};
    unsigned long long C[8]{};
    u128 threshold[8]{};
    u128 best_threshold = 0;
};

static Entry TABLE[256];

static std::string decimal(u128 x) {
    if (!x) return "0";
    std::string s;
    while (x) {
        s.push_back(char('0' + x % 10));
        x /= 10;
    }
    std::reverse(s.begin(), s.end());
    return s;
}

static void build_table() {
    for (unsigned r = 0; r < 256; ++r) {
        unsigned long long x = r;
        unsigned long long A = 1;
        unsigned long long C = 0;
        u128 best = 0;

        for (int t = 0; t < 8; ++t) {
            if (x & 1ULL) {
                A *= 3;
                C = 3 * C + (1ULL << t);
                x = (3 * x + 1) / 2;
            } else {
                x /= 2;
            }

            TABLE[r].A[t] = A;
            TABLE[r].C[t] = C;

            // T^(t+1)(n)=(A*n+C)/2^(t+1).  The threshold is exact.
            u128 numerator = LO << (t + 1);
            u128 th = numerator >= C ? (numerator - C) / A : 0;
            TABLE[r].threshold[t] = th;
            if (th > best) best = th;
        }

        TABLE[r].A8 = A;
        TABLE[r].C8 = C;
        TABLE[r].best_threshold = best;
    }
}

int main(int argc, char **argv) {
    if (argc != 2) {
        std::cerr << "usage: verifier tail_u128.bin\n";
        return 2;
    }

    build_table();
    std::ifstream in(argv[1], std::ios::binary);
    if (!in) {
        std::cerr << "cannot open input\n";
        return 2;
    }

    const u128 UMAX = ~(u128)0;
    unsigned char buf[16];
    unsigned long long records = 0;
    unsigned long long closed = 0;
    unsigned long long failures = 0;
    unsigned long long overflows = 0;
    int max_tail_steps = 0;
    u128 argmax_start = 0;
    u128 max_start = 0;
    u128 max_seen = 0;

    while (in.read(reinterpret_cast<char *>(buf), 16)) {
        u128 n = 0;
        for (int i = 15; i >= 0; --i) n = (n << 8) | buf[i];

        const u128 start = n;
        if (start > max_start) max_start = start;
        int steps = 0;
        bool ok = false;

        for (int block = 0; block < 2000; ++block) {
            if (n <= LO) {
                ok = true;
                break;
            }
            if (n > max_seen) max_seen = n;

            Entry &e = TABLE[(unsigned)(n & 255)];
            if (n <= e.best_threshold) {
                for (int t = 0; t < 8; ++t) {
                    if (n <= e.threshold[t]) {
                        steps += t + 1;
                        ok = true;
                        break;
                    }
                }
                break;
            }

            if (n > (UMAX - (u128)e.C8) / (u128)e.A8) {
                ++overflows;
                break;
            }
            n = ((u128)e.A8 * n + (u128)e.C8) >> 8;
            steps += 8;
        }

        ++records;
        if (ok) {
            ++closed;
            if (steps > max_tail_steps) {
                max_tail_steps = steps;
                argmax_start = start;
            }
        } else {
            ++failures;
        }
    }

    if (records != 11'766'228ULL) return 3;
    if (closed != records || failures != 0 || overflows != 0) return 4;
    if (max_tail_steps != 331) return 5;
    if (max_start != (u128)3974870547266356693ULL * (u128)1000000ULL + 721402ULL) {
        // 3974870547266356693721402, split to avoid a non-standard giant literal.
        return 6;
    }

    std::cout << "records " << records << "\n";
    std::cout << "closed " << closed << "\n";
    std::cout << "failures " << failures << "\n";
    std::cout << "overflows " << overflows << "\n";
    std::cout << "max_tail_steps " << max_tail_steps << "\n";
    std::cout << "argmax_start " << decimal(argmax_start) << "\n";
    std::cout << "max_start " << decimal(max_start) << "\n";
    std::cout << "max_seen " << decimal(max_seen) << "\n";
    std::cout << "PASS MATH-069 r=16 streaming tail descent\n";
    return 0;
}
