#include <boost/multiprecision/cpp_int.hpp>
#include <bits/stdc++.h>
#include <omp.h>
using namespace std; using u128=unsigned __int128; using u64=uint64_t; using boost::multiprecision::cpp_int;
struct S{uint64_t r; u128 y; uint8_t q,k;}; struct T11{uint8_t s; uint64_t c; array<uint8_t,12> pref;}; struct D22{uint8_t jcrit,scrit,stotal;};
static uint64_t L,U; static int FIXK; static const int M11=1<<11,M22=1<<22,MASK22=M22-1,KEND=1029;
int qpub[KEND+23]; u128 p3[64]; cpp_int A,B,pA[23],pB[23],p2i[23];
int cmp(int j1,int s1,int j2,int s2){int dj=j1-j2,ds=s1-s2;if(dj==0)return ds<0?1:(ds>0?-1:0);if(ds==0)return dj>0?1:-1;if(dj>0&&ds<0)return 1;if(dj<0&&ds>0)return -1;if(dj>0){cpp_int lhs=p2i[dj]*pB[ds];return lhs>pA[ds]?1:-1;} cpp_int lhs=p2i[-dj]*pB[-ds];return lhs>pA[-ds]?-1:1;}
uint32_t invodd(uint32_t a){uint32_t x=a;for(int i=0;i<5;++i)x*=2-a*x;return x;}
bool can_hit(uint64_t r,int k){if(k>FIXK||r>U)return false;if(k==FIXK)return r>=L&&r<=U;uint64_t step=1ULL<<k,max_t=(1ULL<<(FIXK-k))-1ULL,lo=0;if(L>r)lo=(L-r+step-1)/step;uint64_t hi=(U-r)/step;return lo<=hi&&lo<=max_t;}
bool step11(u128&n,int&q,const T11*d){int u=int(n&(M11-1));auto de=d[u];u128 UMAX=~u128(0);if(n>(UMAX-de.c)/p3[de.s])return false;n=(p3[de.s]*n+de.c)>>11;q+=de.s;return true;}
int main(int argc,char**argv){if(argc!=4){cerr<<"usage L U FIXK\n";return 2;}L=stoull(argv[1]);U=stoull(argv[2]);FIXK=stoi(argv[3]);B=cpp_int(1)<<71;A=3*B+1;pA[0]=pB[0]=p2i[0]=1;for(int i=1;i<=22;++i){pA[i]=pA[i-1]*A;pB[i]=pB[i-1]*B;p2i[i]=p2i[i-1]*2;}cpp_int two=1,ap=1,bp=1;int qp=0;for(int k=1;k<=KEND+22;++k){two*=2;while(!(ap>two*bp)){ap*=A;bp*=B;++qp;}qpub[k]=qp;}p3[0]=1;for(int i=1;i<64;++i)p3[i]=p3[i-1]*3;
T11 d11[M11];for(int u=0;u<M11;++u){uint64_t n=u;int s=0;array<uint8_t,12> pref{};for(int j=1;j<=11;++j){bool o=n&1;if(o){n=(3*n+1)/2;++s;}else n/=2;pref[j]=s;}uint64_t c=uint64_t(M11)*n-uint64_t(p3[s])*uint64_t(u);d11[u]={uint8_t(s),c,pref};}
vector<D22> desc(M22);vector<uint8_t> H61(M22);for(int u=0;u<M22;++u){uint64_t n=u;int s=0,jc=1,sc=0;array<uint8_t,23> pref{};for(int j=1;j<=22;++j){bool o=n&1;if(o){n=(3*n+1)/2;++s;}else n/=2;pref[j]=s;if(j==1||cmp(j,s,jc,sc)>0){jc=j;sc=s;}}desc[u]={uint8_t(jc),uint8_t(sc),uint8_t(s)};int h=INT_MIN;for(int j=1;j<=22;++j)h=max(h,qpub[61+j]-int(pref[j]));assert(h==qpub[61+jc]-sc);H61[u]=uint8_t(h);}const int Q0=39,Q1=61,NQ=23,WORDS=M22/64;vector<vector<uint64_t>> bits(NQ,vector<uint64_t>(WORDS));uint32_t mult[NQ],inv[NQ];for(int q=Q0;q<=Q1;++q){int qi=q-Q0;mult[qi]=uint32_t(p3[q]&MASK22);inv[qi]=invodd(mult[qi])&MASK22;for(int t=0;t<M22;++t){uint32_t u=uint32_t(uint64_t(mult[qi])*t)&MASK22;if(H61[u]<=q)bits[qi][t>>6]|=1ULL<<(t&63);}}
vector<S> frontier{{0,0,0,0}};for(int k=0;k<10;++k){vector<S> nx;u64 add=1ULL<<k;for(auto st:frontier)for(int e=0;e<=1;++e){u128 z=st.y+(e?p3[st.q]:0);int o=int(z&1),q2=st.q+o;if(q2<qpub[k+1])continue;u128 y2=o?(3*z+1)/2:z/2;uint64_t r2=st.r+(e?add:0);nx.push_back({r2,y2,uint8_t(q2),uint8_t(k+1)});}frontier.swap(nx);}assert(frontier.size()==64);
unsigned long long leaves=0,inst83=0,gates=0;long long survive=0,ovf=0;int deepest=0;unsigned long long witness=~0ULL;uint64_t minr=ULLONG_MAX,maxr=0;array<unsigned long long,64> hist{};
#pragma omp parallel
{unsigned long long ll=0,ii=0,gg=0;long long ss=0,oo=0;int dd=0;unsigned long long ww=~0ULL;uint64_t lmin=ULLONG_MAX,lmax=0;array<unsigned long long,64> hh{};
#pragma omp for schedule(dynamic,1)
for(int fi=0;fi<(int)frontier.size();++fi){vector<S> stack{frontier[fi]};while(!stack.empty()){S st=stack.back();stack.pop_back();if(st.k<FIXK){u64 add=1ULL<<st.k;for(int e=1;e>=0;--e){u128 z=st.y+(e?p3[st.q]:0);int o=int(z&1),q2=st.q+o;if(q2<qpub[st.k+1])continue;u128 y2=o?(3*z+1)/2:z/2;uint64_t r2=st.r+(e?add:0);if(can_hit(r2,st.k+1))stack.push_back({r2,y2,uint8_t(q2),uint8_t(st.k+1)});}continue;}if(st.r<L||st.r>U)continue;u128 y=st.y;int q=st.q;bool ok=true;for(int k=FIXK;k<61;++k){int o=int(y&1);q+=o;if(q<qpub[k+1]){ok=false;break;}y=o?(3*y+1)/2:y/2;}if(!ok)continue;++ll;++hh[q];lmin=min(lmin,st.r);lmax=max(lmax,st.r);int qi=q-Q0;assert(qi>=0&&qi<NQ);uint32_t phase=uint32_t(y&MASK22),z0=uint32_t(uint64_t(inv[qi])*phase)&MASK22,start=(z0+1025u)&MASK22;int remain=339,offset=0;uint32_t pos=start;while(remain){int wi=pos>>6,bo=pos&63,take=min(remain,64-bo);if(pos+take>M22)take=M22-pos;uint64_t word=bits[qi][wi]>>bo;if(take<64)word&=(1ULL<<take)-1;while(word){int bit=__builtin_ctzll(word),delta=offset+bit,b=1025+delta;uint32_t t=(start+delta)&MASK22,u=uint32_t(uint64_t(mult[qi])*t)&MASK22;++ii;u128 n=y+u128(b)*p3[q];int qn=q;bool bad=!step11(n,qn,d11)||!step11(n,qn,d11);if(bad){++oo;word&=word-1;continue;}assert(qn==q+desc[u].stotal);int K=83;for(;K+22<=KEND;K+=22){++gg;uint32_t ur=uint32_t(n&MASK22);auto de=desc[ur];int need=qpub[K+de.jcrit]-de.scrit;if(qn<need)break;if(!step11(n,qn,d11)||!step11(n,qn,d11)){bad=true;++oo;break;}}if(!bad){unsigned long long pack=(uint64_t(st.r)<<16)|uint64_t(b);if(K>dd){dd=K;ww=pack;}else if(K==dd){ww=min(ww,pack);}if(K+22>KEND)++ss;}word&=word-1;}remain-=take;offset+=take;pos=(pos+take)&MASK22;}}}
#pragma omp critical
{leaves+=ll;inst83+=ii;gates+=gg;survive+=ss;ovf+=oo;if(dd>deepest){deepest=dd;witness=ww;}else if(dd==deepest){witness=min(witness,ww);}minr=min(minr,lmin);maxr=max(maxr,lmax);for(int q=0;q<64;++q)hist[q]+=hh[q];}}
cout<<"leaves="<<leaves<<" min="<<minr<<" max="<<maxr<<" inst83="<<inst83<<" gates="<<gates<<" survive="<<survive<<" ovf="<<ovf<<" deepest="<<deepest<<"\n";if(witness!=~0ULL)cout<<"wit="<<(witness>>16)<<","<<(witness&0xffffULL)<<"\n";for(int q=0;q<64;++q)if(hist[q])cout<<q<<":"<<hist[q]<<"\n";
}
