#!/usr/bin/env python3
"""
A0 s=1 late-shell checkpoint candidate reducer certificate.

Purpose
-------
Given a *coherent ordinary checkpoint integer* Z in the certified checkpoint
corridor, reduce the five late surviving first-defect shells
f in {27,29,32,35,37} to exact finite ordinary-X candidate sets.

This certificate is deliberately conditional on Z already being coherent.
It does NOT prove that any pair of exposed dyadic/ternary checkpoint residues
is generated by the same admissible long correction/tail object.

It also certifies the special f=37 threshold:
because the debit corridor is shorter than 3*2^38, f=37 induces a genuine
periodic ordinary-Z exclusion sieve.

Classification
--------------
EXACT:
  * finite-candidate reducer for fixed ordinary Z;
  * universal candidate caps {330,83,11,2,1};
  * f=37 checkpoint residue interval modulo 3*2^38;
  * exact checkpoint-corridor allowed/eliminated counts for f=37.

OPEN:
  * production of coherent (Z mod 2^27, Z mod 3^28) by one admissible
    long correction/tail object;
  * full correction-language membership;
  * global Collatz conclusion.
"""

from __future__ import annotations

from dataclasses import dataclass

X_TH = 4_697_939_311_072_332_635_131
X_MIN = 2**71 + 1
X_MAX = 3_234_977_022_306_677_631_165

L_MIN = 669_562_762_561
L_MAX = 934_928_480_993
L_SPAN = L_MAX - L_MIN

Z_MIN = 7_083_549_723_369_539_339_554
Z_MAX = 9_444_732_965_739_290_427_391

LATE_F = (27, 29, 32, 35, 37)
EXPECTED_CAPS = {27: 330, 29: 83, 32: 11, 35: 2, 37: 1}

F37_PERIOD = 3 * 2**38
F37_RES_LO = 41_593_248_016
F37_RES_HI = 306_958_966_448
F37_ALLOWED_Z = 759_824_721_786_673_869_356
F37_ELIMINATED_Z = 1_601_358_520_583_077_218_482


def ceil_div(a: int, b: int) -> int:
    return -((-a) // b)


def first_congruent_at_or_above(lo: int, residue: int, modulus: int) -> int:
    return lo + ((residue - lo) % modulus)


def last_congruent_at_or_below(hi: int, residue: int, modulus: int) -> int:
    return hi - ((hi - residue) % modulus)


def shell_residue(f: int) -> tuple[int, int]:
    modulus = 2 ** (f + 1)
    residue = (X_TH + 2**f) % modulus
    return residue, modulus


@dataclass(frozen=True)
class CandidateSet:
    f: int
    lo: int
    hi: int
    residue: int
    modulus: int
    first: int | None
    last: int | None
    count: int


def candidates_for_z(z: int, f: int) -> CandidateSet:
    assert Z_MIN <= z <= Z_MAX
    residue, modulus = shell_residue(f)

    lo = max(X_MIN, ceil_div(z + L_MIN, 3))
    hi = min(X_MAX, (z + L_MAX) // 3)

    if lo > hi:
        return CandidateSet(f, lo, hi, residue, modulus, None, None, 0)

    first = first_congruent_at_or_above(lo, residue, modulus)
    if first > hi:
        return CandidateSet(f, lo, hi, residue, modulus, None, None, 0)

    last = last_congruent_at_or_below(hi, residue, modulus)
    count = (last - first) // modulus + 1
    return CandidateSet(f, lo, hi, residue, modulus, first, last, count)


def universal_cap(f: int) -> int:
    _, modulus = shell_residue(f)
    # Consecutive shell X-values are modulus apart; at fixed Z their debits
    # L_- = 3X-Z are therefore 3*modulus apart.
    return L_SPAN // (3 * modulus) + 1


def count_interval_residue_band(
    lo: int, hi: int, period: int, a: int, b: int
) -> int:
    """Count n in [lo,hi] with n mod period in the non-wrapping band [a,b]."""
    assert 0 <= a <= b < period

    def prefix(n: int) -> int:
        if n < 0:
            return 0
        q, r = divmod(n, period)
        return q * (b - a + 1) + max(0, min(r, b) - a + 1)

    return prefix(hi) - prefix(lo - 1)


def f37_residue_band() -> tuple[int, int, int]:
    f = 37
    r, modulus = shell_residue(f)
    period = 3 * modulus
    assert period == F37_PERIOD
    assert L_SPAN + 1 < period

    # X = r + modulus*k and Z = 3X-L_- imply
    # Z == 3r-L_- (mod 3*modulus).
    lo = (3 * r - L_MAX) % period
    hi = (3 * r - L_MIN) % period
    assert lo <= hi  # no wrap for the actual A0 constants
    return period, lo, hi


def direct_f37_exists(z: int) -> bool:
    return candidates_for_z(z, 37).count == 1


def main() -> None:
    assert X_MIN <= X_MAX
    assert L_MIN <= L_MAX
    assert Z_MIN <= Z_MAX

    # Universal late-shell caps.
    got_caps = {f: universal_cap(f) for f in LATE_F}
    assert got_caps == EXPECTED_CAPS

    # f=37 is the first surviving late shell whose debit corridor is shorter
    # than the debit stride 3*2^(f+1). f=35 still overlaps.
    assert L_SPAN + 1 >= 3 * 2**36
    assert L_SPAN + 1 < 3 * 2**38

    period, band_lo, band_hi = f37_residue_band()
    assert period == F37_PERIOD
    assert band_lo == F37_RES_LO
    assert band_hi == F37_RES_HI
    assert band_hi - band_lo + 1 == L_SPAN + 1

    allowed = count_interval_residue_band(
        Z_MIN, Z_MAX, period, band_lo, band_hi
    )
    total = Z_MAX - Z_MIN + 1
    eliminated = total - allowed
    assert allowed == F37_ALLOWED_Z
    assert eliminated == F37_ELIMINATED_Z

    # Regression at all relevant boundaries: residue-band membership and the
    # direct ordinary-X candidate reducer agree.
    probes = {
        Z_MIN,
        Z_MIN + 1,
        Z_MAX - 1,
        Z_MAX,
    }
    q0 = Z_MIN // period
    q1 = Z_MAX // period
    for q in {q0, q0 + 1, q1 - 1, q1}:
        for edge in (
            band_lo - 1,
            band_lo,
            band_lo + 1,
            band_hi - 1,
            band_hi,
            band_hi + 1,
        ):
            z = q * period + edge
            if Z_MIN <= z <= Z_MAX:
                probes.add(z)

    for z in sorted(probes):
        residue_ok = band_lo <= (z % period) <= band_hi
        assert direct_f37_exists(z) == residue_ok

    # General reducer sanity and exact debit reconstruction on a set of edge
    # and central checkpoints.
    z_probes = [Z_MIN, Z_MIN + 1, (Z_MIN + Z_MAX) // 2, Z_MAX - 1, Z_MAX]
    for z in z_probes:
        for f in LATE_F:
            cs = candidates_for_z(z, f)
            assert cs.count <= EXPECTED_CAPS[f]
            if cs.count:
                assert cs.first is not None and cs.last is not None
                x = cs.first
                seen = 0
                while x <= cs.last:
                    assert X_MIN <= x <= X_MAX
                    r, m = shell_residue(f)
                    assert x % m == r
                    debit = 3 * x - z
                    assert L_MIN <= debit <= L_MAX
                    seen += 1
                    x += m
                assert seen == cs.count

    print("A0 s=1 late-shell checkpoint reducer: PASS")
    print("caps:", got_caps)
    print("f37 period:", period)
    print("f37 allowed residue band:", (band_lo, band_hi))
    print("f37 checkpoint total:", total)
    print("f37 allowed:", allowed)
    print("f37 eliminated:", eliminated)


if __name__ == "__main__":
    main()
