#!/usr/bin/env python3
"""Fourier transfer for the oriented Beatty boundary of Collatz coefficient survival.

This is a diagnostic / reproducibility program, not a proof of a uniform
spectral gap.  All Beatty barriers are generated by exact integer comparisons.
Complex phases use ordinary floating point.

For the accelerated Collatz map, a length-k parity word coefficient-survives iff
    3^q_j >= 2^j
at every prefix j.  Suppose the Beatty barrier rises at the final step:
    b_k = b_(k-1) + 1.
Then a one-child parent at depth k-1 is exactly a surviving prefix with
q_(k-1)=b_(k-1), and its unique surviving child is odd.

On the reduced child coordinate y=(r-3)/4 mod 2^(k-2), extend the boundary
orientation anti-periodically so that w=+1 on the surviving odd child and w=-1
on its rejected even sibling.  For odd Fourier frequency t,

    w_hat(t)/2

is the character sum over the surviving odd boundary children.  Hence this
program computes the normalized coefficient

    (1/B_k) sum_boundary exp(2 pi i t y / 2^(k-2)),

whose magnitude is |w_hat(t)|/(2 B_k).
"""

from __future__ import annotations

import argparse
import cmath
import math


def qmins_exact(k: int) -> list[int]:
    """b[j] = least q with 3^q >= 2^j, by exact integer arithmetic."""
    b = [0] * (k + 1)
    q = 0
    p3 = 1
    for j in range(1, k + 1):
        target = 1 << j
        while p3 < target:
            q += 1
            p3 *= 3
        b[j] = q
    return b


def boundary_count(k: int) -> int:
    b = qmins_exact(k)
    if b[k] != b[k - 1] + 1:
        return 0
    target_parent_q = b[k] - 1
    counts = [1]
    for j in range(k - 1):
        threshold = b[j + 1]
        nxt = [0] * (j + 2)
        for q_old, c in enumerate(counts):
            if not c:
                continue
            if q_old >= threshold:
                nxt[q_old] += c
            if q_old + 1 >= threshold:
                nxt[q_old + 1] += c
        counts = nxt
    return counts[target_parent_q]


def normalized_boundary_fourier(k: int, t: int) -> complex:
    """Normalized Fourier coefficient of surviving odd boundary children."""
    if t % 2 == 0:
        raise ValueError("t must be odd for the oriented boundary identity")
    b = qmins_exact(k)
    if b[k] != b[k - 1] + 1:
        raise ValueError("k is not a Beatty barrier-rise child depth")

    target_parent_q = b[k] - 1

    # p[q], a[q] are unweighted / weighted prefix masses after common
    # normalization.  Their ratio is therefore invariant under renormalization.
    p = [1.0]
    a = [1.0 + 0.0j]

    for j in range(k - 1):
        threshold = b[j + 1]
        remaining = k - j
        modulus = 1 << remaining
        inv3 = pow(3, -1, modulus)

        invpow = [1] * (j + 2)
        for q in range(1, j + 2):
            invpow[q] = (invpow[q - 1] * inv3) % modulus

        np = [0.0] * (j + 2)
        na = [0.0j] * (j + 2)

        for q_old in range(j + 1):
            pv = p[q_old]
            av = a[q_old]
            if pv == 0.0 and av == 0.0j:
                continue

            if q_old >= threshold:
                np[q_old] += pv
                na[q_old] += av

            q_new = q_old + 1
            if q_new >= threshold:
                frac = invpow[q_new] / modulus
                phase = cmath.exp(-2j * math.pi * t * frac)
                np[q_new] += pv
                na[q_new] += av * phase

        z = sum(np)
        if z == 0.0:
            return 0.0j
        p = [x / z for x in np]
        a = [x / z for x in na]

    if target_parent_q >= len(p) or p[target_parent_q] == 0.0:
        return 0.0j

    # Final step is forced odd.  At the final character scale the odd phase is
    # exp(-2*pi*i*t/2)=-1 for odd t.  It does not affect the magnitude.
    final_phase = -1.0 + 0.0j
    return final_phase * a[target_parent_q] / p[target_parent_q]


def next_rise_at_or_after(k0: int) -> int:
    for k in range(max(2, k0), k0 + 10):
        b = qmins_exact(k)
        if b[k] == b[k - 1] + 1:
            return k
    raise RuntimeError("unexpectedly long Beatty plateau")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("k", type=int, help="target child depth; next rise is used if needed")
    ap.add_argument("--odd-max", type=int, default=31,
                    help="scan positive odd frequencies through this value")
    args = ap.parse_args()

    k = next_rise_at_or_after(args.k)
    B = boundary_count(k)
    print(f"requested_k={args.k} rise_k={k} boundary_count={B}")

    best = None
    for t in range(1, args.odd_max + 1, 2):
        z = normalized_boundary_fourier(k, t)
        mag = abs(z)
        rate = float("inf") if mag == 0.0 else -math.log2(mag) / k
        print(f"t={t:5d} abs_boundary_hat={mag:.17e} rate_bits_per_step={rate:.15f}")
        if best is None or mag > best[1]:
            best = (t, mag, rate)

    if best:
        print(f"worst_t={best[0]} worst_abs_hat={best[1]:.17e} worst_rate={best[2]:.15f}")


if __name__ == "__main__":
    main()
