#include <algorithm>
#include <cstdint>
#include <iostream>
#include <map>
#include <string>
#include <unordered_set>
#include <vector>

using i128 = __int128_t;
using u128 = __uint128_t;
using u64 = std::uint64_t;

// Exact finite certificate for the Delta-Q=1 two-channel Collatz problem.
//
// H has q+1 odd positions 0=a_0<a_1<...<a_q.
// L has q   odd positions 0=b_0<b_1<...<b_{q-1}.
// Coefficient survival implies
//     a_i <= kappa(i), b_i <= kappa(i),
// where kappa(i)=floor(i log_2 3). kappa is generated by exact integer
// comparison, never floating point.
//
// For a common-endpoint pair define the 3-adic carry by
//     c_q = 0,
//     3 c_i = 2^{a_{i+1}} - 2^{b_i} + c_{i+1},
// and G=1+c_0. A dominance failure r_H >= r_L is possible only for G<0,
// since at Delta-Q=1
//     r_L-r_H = 2 r_H + G.
//
// This program first builds every carry state compatible with the individual
// coefficient-survival position bounds and terminal divisibility c_q=0.
// It reports the complete negative root spectrum at (a_1,b_0)=(1,0).
//
// In full mode it then reconstructs only negative-root paths. Along each path
// it accumulates the correction numerators
//     R_H(i+1)=3 R_H(i)+2^{a_{i+1}},
//     R_L(i)  =3 R_L(i-1)+2^{b_i}.
// A true first-merge candidate must have different last parities, hence
//     k = max(a_q,b_{q-1})+1,
// and must still satisfy k <= kappa(q).
// Canonical residues at that k are recovered exactly modulo 2^k. The binary
// wrap index is
//     m = (r_L - 3 r_H - G)/2^k.
// m=0 is exactly the common-endpoint condition. Such candidates are finally
// checked for the actual Pareto failure r_H >= r_L.
//
// Usage:
//   deltaq1_carry_wrap_dominance q [--roots-only]
//
// Current implementation intentionally limits q<=40 so all powers used in the
// finite certificate fit comfortably in unsigned/signed 128-bit arithmetic.

struct CarryKey {
    int A = 0;
    int B = 0;
    i128 c = 0;
    bool operator==(const CarryKey& o) const {
        return A == o.A && B == o.B && c == o.c;
    }
};

static u64 low64(i128 x) { return static_cast<u64>(static_cast<u128>(x)); }
static u64 high64(i128 x) { return static_cast<u64>(static_cast<u128>(x) >> 64); }

struct CarryHash {
    std::size_t operator()(const CarryKey& x) const {
        u64 h = static_cast<u64>(x.A) * 0x9e3779b97f4a7c15ULL;
        h ^= static_cast<u64>(x.B) * 0xbf58476d1ce4e5b9ULL;
        h ^= low64(x.c);
        h ^= high64(x.c) + 0x94d049bb133111ebULL + (h << 6) + (h >> 2);
        return static_cast<std::size_t>(h);
    }
};

struct PathNode {
    int A = 0;
    int B = 0;
    i128 c = 0;
    i128 RH = 0;
    i128 RL = 0;
};

static i128 pow2i(int n) { return static_cast<i128>(1) << n; }

static i128 pow3i(int n) {
    i128 x = 1;
    for (int i = 0; i < n; ++i) x *= 3;
    return x;
}

static long long to_ll(i128 x) { return static_cast<long long>(x); }

// Newton iteration for an odd inverse modulo 2^k. The unsigned 128-bit wrap
// supplies the 2-adic iteration; the final mask restricts to the requested k.
static u128 inv_odd_mod_pow2(u128 a, int k) {
    u128 x = 1;
    for (int bits = 1; bits < k; bits *= 2) x = x * (2 - a * x);
    const u128 mask = (static_cast<u128>(1) << k) - 1;
    return x & mask;
}

int main(int argc, char** argv) {
    const int q = (argc >= 2 ? std::stoi(argv[1]) : 28);
    const bool roots_only = (argc >= 3 && std::string(argv[2]) == "--roots-only");
    if (q < 2 || q > 40) {
        std::cerr << "q must satisfy 2 <= q <= 40\n";
        return 1;
    }

    // Exact kappa(i)=floor(i log_2 3), using 2^k < 3^i < 2^(k+1).
    std::vector<int> kappa(q + 1, 0);
    u128 p3 = 1;
    u128 p2 = 1;
    int kk = 0;
    for (int i = 1; i <= q; ++i) {
        p3 *= 3;
        while ((p2 << 1) < p3) {
            p2 <<= 1;
            ++kk;
        }
        kappa[i] = kk;
    }

    std::vector<std::unordered_set<CarryKey, CarryHash>> viable(q);

    // Terminal layer: c_q=0, so 3 c_{q-1}=2^{a_q}-2^{b_{q-1}}.
    for (int A = q; A <= kappa[q]; ++A) {
        for (int B = q - 1; B <= kappa[q - 1]; ++B) {
            const i128 z = pow2i(A) - pow2i(B);
            if (z % 3 == 0) viable[q - 1].insert({A, B, z / 3});
        }
    }

    std::size_t peak_states = viable[q - 1].size();

    // Backward carry transfer toward i=0, preserving strict odd-position order.
    for (int i = q - 2; i >= 0; --i) {
        auto& here = viable[i];
        here.reserve(viable[i + 1].size() * 2 + 1024);
        for (const CarryKey& next : viable[i + 1]) {
            const int Amax = std::min(kappa[i + 1], next.A - 1);
            const int Bmax = std::min(kappa[i], next.B - 1);
            for (int A = i + 1; A <= Amax; ++A) {
                for (int B = i; B <= Bmax; ++B) {
                    const i128 z = pow2i(A) - pow2i(B) + next.c;
                    if (z % 3 == 0) here.insert({A, B, z / 3});
                }
            }
        }
        peak_states = std::max(peak_states, here.size());
    }

    std::vector<i128> negative_roots;
    for (const CarryKey& x : viable[0]) {
        if (x.A == 1 && x.B == 0 && x.c < 0) negative_roots.push_back(x.c);
    }
    std::sort(negative_roots.begin(), negative_roots.end());

    std::cout << "q=" << q
              << ",kappa=" << kappa[q]
              << ",peak_carry_states=" << peak_states
              << ",root_states=" << viable[0].size()
              << ",negative_roots=" << negative_roots.size() << '\n';
    for (i128 c0 : negative_roots) {
        std::cout << "root_c0=" << to_ll(c0)
                  << ",G=" << to_ll(1 + c0) << '\n';
    }

    if (roots_only || negative_roots.empty()) return 0;

    u64 negative_paths = 0;
    u64 true_negative_merges = 0;
    u64 dominance_failures = 0;
    u64 typeA = 0, typeB = 0, equal_last = 0, survival_depth_fail = 0;
    i128 min_J = static_cast<i128>(1) << 120;
    std::map<long long, u64> G_hist;

    for (i128 c0 : negative_roots) {
        // a_0=b_0=0 and coefficient survival forces a_1=1.
        std::vector<PathNode> paths{{1, 0, c0, 5, 1}};

        for (int i = 0; i < q - 1; ++i) {
            std::vector<PathNode> next_paths;
            for (const PathNode& n : paths) {
                const i128 cnext = 3 * n.c - pow2i(n.A) + pow2i(n.B);
                for (int A2 = n.A + 1; A2 <= kappa[i + 2]; ++A2) {
                    const i128 RH2 = 3 * n.RH + pow2i(A2);
                    for (int B2 = n.B + 1; B2 <= kappa[i + 1]; ++B2) {
                        if (viable[i + 1].find({A2, B2, cnext}) == viable[i + 1].end())
                            continue;
                        const i128 RL2 = 3 * n.RL + pow2i(B2);
                        next_paths.push_back({A2, B2, cnext, RH2, RL2});
                    }
                }
            }
            paths.swap(next_paths);
        }

        negative_paths += static_cast<u64>(paths.size());
        const i128 G = 1 + c0;
        const i128 p3q = pow3i(q);
        const i128 p3h = 3 * p3q;

        for (const PathNode& n : paths) {
            if (n.A == n.B) {
                ++equal_last;
                continue;
            }

            // Different final odd positions encode the two possible last-step
            // types. The larger position is exactly k-1 at first contact.
            const int k = std::max(n.A, n.B) + 1;
            if (k > kappa[q]) {
                ++survival_depth_fail;
                continue;
            }
            if (n.A > n.B) ++typeA;
            else ++typeB;

            const u128 mod = static_cast<u128>(1) << k;
            const u128 mask = mod - 1;
            const u128 invH = inv_odd_mod_pow2(static_cast<u128>(p3h), k);
            const u128 invL = inv_odd_mod_pow2(static_cast<u128>(p3q), k);
            const u128 rH = (0 - static_cast<u128>(n.RH) * invH) & mask;
            const u128 rL = (0 - static_cast<u128>(n.RL) * invL) & mask;

            const i128 Gstart = static_cast<i128>(rL) - 3 * static_cast<i128>(rH);
            const i128 diff = Gstart - G;
            if (diff % static_cast<i128>(mod) != 0) {
                std::cerr << "2-adic congruence failure\n";
                return 2;
            }
            const i128 wrap = diff / static_cast<i128>(mod);
            if (wrap != 0) continue;

            ++true_negative_merges;
            ++G_hist[to_ll(G)];

            const i128 J = static_cast<i128>(rL) - static_cast<i128>(rH);
            min_J = std::min(min_J, J);
            if (J <= 0) {
                ++dominance_failures;
                if (dominance_failures <= 3) {
                    std::cout << "DOMINANCE_FAILURE"
                              << ",k=" << k
                              << ",G=" << to_ll(G)
                              << ",rH=" << static_cast<u64>(rH)
                              << ",rL=" << static_cast<u64>(rL)
                              << ",a_q=" << n.A
                              << ",b_last=" << n.B << '\n';
                }
            }
        }
    }

    std::cout << "negative_paths=" << negative_paths
              << ",typeA=" << typeA
              << ",typeB=" << typeB
              << ",equal_last=" << equal_last
              << ",survival_depth_fail=" << survival_depth_fail
              << ",true_negative_G_merges=" << true_negative_merges
              << ",dominance_failures=" << dominance_failures;
    if (true_negative_merges) std::cout << ",min_J=" << to_ll(min_J);
    std::cout << '\n';

    std::cout << "G_hist";
    for (const auto& kv : G_hist) std::cout << ",G" << kv.first << '=' << kv.second;
    std::cout << '\n';
    return 0;
}
