#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdlib>
#include <iomanip>
#include <iostream>
#include <unordered_map>
#include <vector>
#include <limits>
#include <omp.h>
using u64=uint64_t; using u32=uint32_t; using u128=__uint128_t;
static constexpr int H=24, ZBITS=22, ZM=1<<22, ZMASK=ZM-1, BMAX=23, KMAX=36, LOWZBITS=22, LOWZMASK=(1u<<22)-1;
struct State{u64 R; uint8_t q;}; struct Fwd{u64 R; uint8_t q; bool odd;}; struct E{u64 C=0; uint8_t q=0,K=0; bool valid=false;};
u64 p3[50];
inline bool coeffok(int k,int q){return p3[q]>=(1ULL<<k);} inline u64 ckey(int q,u64 R){return (u64(q)<<56)|(R%p3[q]);}
void scanall(int pos,int k,int q,u64 R,int qmin,std::unordered_map<u64,u64>&cm){if(q+(k-pos)<qmin)return;if(pos==k){auto it=cm.find(ckey(q,R));if(it!=cm.end()&&R>it->second)it->second=R;return;}scanall(pos+1,k,q,R,qmin,cm);scanall(pos+1,k,q+1,3*R+(1ULL<<pos),qmin,cm);}
u64 invodd(u64 a){u64 x=a;for(int i=0;i<6;++i)x*=2-a*x;return x;}
std::vector<u32> rootH24(){const u64 exp[25]={0,1,1,2,3,4,7,11,16,31,52,103,182,297,593,1049,1720,3439,6104,12194,22244,38019,75969,137657,234156};std::vector<State>coef{{0,0}},nest{{0,0}};for(int k=1;k<=H;++k){std::vector<State>nc;nc.reserve(coef.size()*2);for(auto s:coef){if(coeffok(k,s.q))nc.push_back(s);int q=s.q+1;u64 R=3*s.R+(1ULL<<(k-1));if(coeffok(k,q))nc.push_back({R,(uint8_t)q});}coef.swap(nc);std::unordered_map<u64,u64>cm;cm.reserve(coef.size()*2);for(auto s:coef){auto[it,ins]=cm.emplace(ckey(s.q,s.R),s.R);if(!ins&&s.R>it->second)it->second=s.R;}int qmin=0;while(!coeffok(k,qmin))++qmin;scanall(0,k,0,0,qmin,cm);std::vector<State>nn;nn.reserve(nest.size()*2);for(auto s:nest){if(coeffok(k,s.q)){auto it=cm.find(ckey(s.q,s.R));if(it!=cm.end()&&it->second==s.R)nn.push_back(s);}int q=s.q+1;u64 R=3*s.R+(1ULL<<(k-1));if(coeffok(k,q)){auto it=cm.find(ckey(q,R));if(it!=cm.end()&&it->second==R)nn.push_back({R,(uint8_t)q});}}nest.swap(nn);if(nest.size()!=exp[k])exit(2);}std::vector<u32>z;z.reserve(nest.size());std::vector<uint8_t>seen(ZM);for(auto s:nest){u32 N=(u32)(((0ULL-s.R)*invodd(p3[s.q]))&((1ULL<<H)-1));if((N&3)!=3)exit(3);u32 a=(N-3)>>2;if(seen[a])exit(4);seen[a]=1;z.push_back(a);}std::sort(z.begin(),z.end());return z;}
Fwd forward(u32 r,int B){u64 n=r,R=0;int q=0;for(int k=0;k<B;++k){if(n&1){R=3*R+(1ULL<<k);++q;n=(3*n+1)>>1;}else n>>=1;}return{R,(uint8_t)q,bool(n&1)};}
bool ratio_better(const E&a,const E&b){if(!a.valid)return false;if(!b.valid)return true;u64 L=p3[a.q]*(1ULL<<b.K),R=p3[b.q]*(1ULL<<a.K);if(L!=R)return L>R;return a.C>b.C;}
std::vector<std::vector<E>> buildReverseDP(int Qmax){std::vector<std::vector<E>>keep(Qmax+1);int prevM=1;std::vector<E>prev(prevM*(KMAX+1));for(int d=1;d<=Qmax;++d){int M=prevM*3;std::vector<E>cur((size_t)M*(KMAX+1));for(int z=0;z<M;++z){int r3=z%3;if(r3==0)continue;int a0=(r3==1)?2:1;for(int bud=1;bud<=KMAX;++bud){E best;for(int a=a0;a<=bud;a+=2){u64 num=(1ULL<<a)*(u64)z-1;int zp=prevM>1?int((num/3)%prevM):0;E cand,suf=prev[(size_t)zp*(KMAX+1)+(bud-a)];bool use=suf.valid&&p3[suf.q]>(1ULL<<suf.K);cand.valid=true;if(use){cand.q=suf.q+1;cand.K=suf.K+a;cand.C=(1ULL<<suf.K)+3*suf.C;}else{cand.q=1;cand.K=a;cand.C=1;}if(ratio_better(cand,best))best=cand;}cur[(size_t)z*(KMAX+1)+bud]=best;}}keep[d]=cur;prev.swap(cur);prevM=M;}return keep;}
long long egcd(long long a,long long b,long long&x,long long&y){if(!b){x=1;y=0;return a;}long long x1,y1;long long g=egcd(b,a%b,x1,y1);x=y1;y=x1-y1*(a/b);return g;}int invmod(int a,int m){long long x,y;egcd(a,m,x,y);x%=m;if(x<0)x+=m;return(int)x;}
using i128=__int128_t; static i128 NMIN_G,NMAX_G;
bool exact_candidate_kill(const E&e,const Fwd&f,int B){if(!e.valid)return false;i128 coeff=(i128(1)<<e.K)*i128(p3[f.q]);i128 denom=(i128(1)<<B)*i128(p3[e.q]);i128 con=(i128(1)<<e.K)*i128(f.R)-i128(e.C)*(i128(1)<<B);if(con<0){i128 need=-con;if(!(coeff>need/NMIN_G))return false;}i128 slope=coeff-denom;if(slope<0){i128 a=-slope;if(con<=0)return true;return a>con/NMIN_G;}if(slope==0)return con<0;if(con>=0)return false;i128 need=-con;return slope<=(need-1)/NMAX_G;}
struct C23{std::vector<u64>b22,b23;u64 t22=0,t23=0;};
C23 calc23(int Q,const std::vector<E>&rev,const std::vector<u32>&rootz,const std::vector<std::array<Fwd,BMAX+1>>&paths){int MOD=p3[Q];std::vector<int>inv2(BMAX+1);int tw=1;for(int B=1;B<=BMAX;++B){tw=(long long)tw*2%MOD;inv2[B]=invmod(tw,MOD);}std::vector<u64>dp(ZM),nd(ZM);dp[0]=1;u32 w=1;for(int i=0;i<44;++i){if(i)w=(u64)w*3&ZMASK;if(i<Q)continue;for(u32 r=0;r<ZM;++r)nd[r]=dp[r]+dp[(r+ZM-w)&ZMASK];dp.swap(nd);}int NM=1<<Q;std::vector<u32>low(NM);std::vector<int>n3(NM);for(int m=0;m<NM;++m){u64 sh=0,pw=1;int t=3%MOD;for(int i=0;i<Q;++i){if(m>>i&1){sh+=pw;t=(t+4*(pw%MOD))%MOD;}pw*=3;}low[m]=sh&ZMASK;n3[m]=t;}u32 fixed=1;for(int i=0;i<44;++i)fixed=(u64)fixed*3&ZMASK;C23 o;o.b22.assign(NM,0);o.b23.assign(NM,0);
#pragma omp parallel for schedule(dynamic,1)
for(int lm=0;lm<NM;++lm){u32 base=(fixed+low[lm])&ZMASK;int nm=n3[lm];u64 c22=0,c23=0;for(size_t j=0;j<rootz.size();++j){u64 mult=dp[(rootz[j]+ZM-base)&ZMASK];bool alive=true;for(int B=2;B<=BMAX;++B){if(alive){const Fwd&f=paths[j][B];if(f.odd){int z=((p3[f.q]%MOD)*(u64)nm+f.R%MOD)%MOD;z=(long long)z*inv2[B]%MOD;const E&e=rev[(size_t)z*(KMAX+1)+KMAX];if(exact_candidate_kill(e,f,B))alive=false;}}if(B==22&&alive)c22+=mult;if(B==23&&alive)c23+=mult;} }o.b22[lm]=c22;o.b23[lm]=c23;}for(auto x:o.b22)o.t22+=x;for(auto x:o.b23)o.t23+=x;return o;}
void cmp23(const C23&c,int Q){long double mi=1e100L,ma=-1;int mim=-1,mam=-1,eq=0;u64 minN=0,minD=1,maxN=0,maxD=1;for(int m=0;m<(1<<Q);++m){u64 d=c.b22[m],n=c.b23[m];if(!d)continue;long double r=(long double)n/d;if(r<mi){mi=r;mim=m;minN=n;minD=d;}if(r>ma){ma=r;mam=m;maxN=n;maxD=d;}if(n==d)eq++;}std::cout<<std::setprecision(18)<<"Q"<<Q<<" B22 "<<c.t22<<" B23 "<<c.t23<<" global "<<(long double)c.t23/c.t22<<" min "<<mi<<" m "<<mim<<" "<<minN<<"/"<<minD<<" max "<<ma<<" m "<<mam<<" "<<maxN<<"/"<<maxD<<" equal "<<eq<<"\n";}
int main(){p3[0]=1;for(int i=1;i<50;++i)p3[i]=p3[i-1]*3ULL;i128 P=1;for(int i=0;i<44;++i)P*=3;NMIN_G=4*P+3;NMAX_G=6*P+1;omp_set_num_threads(5);auto rz=rootH24();std::vector<std::array<Fwd,BMAX+1>>paths(rz.size());for(size_t j=0;j<rz.size();++j){u32 r=(4u*(rz[j]&LOWZMASK)+3u)&((1u<<(BMAX+1))-1);for(int B=2;B<=BMAX;++B)paths[j][B]=forward(r&((1u<<(B+1))-1),B);}auto all=buildReverseDP(9);for(int Q=7;Q<=9;++Q){auto c=calc23(Q,all[Q],rz,paths);cmp23(c,Q);}return 0;}
