#!/usr/bin/env python3
"""Exact finite diagnostic for integer predecessor credits in Euclidean macroblocks.

For each listed deterministic mechanical macroblock U, inspect the exact
survival-state fibre

    (Sigma, M) = (-1, -1),

so the actual word has one fewer odd symbol than U and needs only one unit
of incoming Beatty slack.

Within that fibre, words with corrections in the same residue class modulo
3^q have an integer alternate-predecessor relation.  If R_hi > R_lo and

    R_hi - R_lo = 3^q * Delta,

then the low-correction orientation has predecessor credit Delta.

All arithmetic is exact.  The macroblocks are the first return-word
representatives generated by the Euclidean hierarchy already recorded in
the repository.
"""

from collections import defaultdict, Counter
from itertools import combinations


MACROBLOCKS = [
    "101",
    "01101",
    "01101101",
    "10101101101",
    "1010110110101101101",
]

EXPECTED = {
    "101": (3, 2, 1, 3, 2, 1, 1),
    "01101": (5, 3, 2, 9, 5, 4, 2),
    "01101101": (8, 5, 4, 53, 30, 23, 3),
    "10101101101": (11, 7, 6, 299, 179, 120, 5),
    "1010110110101101101": (19, 12, 11, 35174, 21856, 13318, 11),
}


def correction_from_positions(positions: tuple[int, ...]) -> int:
    q = len(positions)
    total = 0
    for j, pos in enumerate(positions):
        total += (1 << pos) * (3 ** (q - 1 - j))
    return total


def relative_state(word_positions: set[int], mechanical: str) -> tuple[int, int]:
    height = 0
    minimum = 0
    for i, ch in enumerate(mechanical):
        actual = 1 if i in word_positions else 0
        reference = 1 if ch == "1" else 0
        height += actual - reference
        minimum = min(minimum, height)
    return height, minimum


def analyze(mechanical: str):
    L = len(mechanical)
    q_star = mechanical.count("1")
    q = q_star - 1
    modulus = 3 ** q

    buckets: dict[int, list[int]] = defaultdict(list)
    fibre_count = 0

    for positions in combinations(range(L), q):
        pos_set = set(positions)
        sigma, minimum = relative_state(pos_set, mechanical)
        if (sigma, minimum) != (-1, -1):
            continue

        R = correction_from_positions(positions)
        buckets[R % modulus].append(R)
        fibre_count += 1

    covered = 0
    max_credit = 0
    credit_hist = Counter()
    best_pair = None

    for residue, values in buckets.items():
        values.sort()
        highest = values[-1]
        for R in values[:-1]:
            credit = (highest - R) // modulus
            assert highest - R == credit * modulus
            if credit > 0:
                covered += 1
                credit_hist[credit] += 1
                if credit > max_credit:
                    max_credit = credit
                    best_pair = (residue, R, highest)

    return {
        "L": L,
        "q_star": q_star,
        "q": q,
        "fibre": fibre_count,
        "residue_classes": len(buckets),
        "covered": covered,
        "max_credit": max_credit,
        "best_pair": best_pair,
        "hist": credit_hist,
    }


def main():
    print("macroblock L q* q fibre residue_classes covered coverage max_credit best_pair")

    for mechanical in MACROBLOCKS:
        out = analyze(mechanical)
        expected = EXPECTED[mechanical]
        got = (
            out["L"],
            out["q_star"],
            out["q"],
            out["fibre"],
            out["residue_classes"],
            out["covered"],
            out["max_credit"],
        )
        assert got == expected, (mechanical, got, expected)

        coverage = out["covered"] / out["fibre"]
        print(
            mechanical,
            out["L"],
            out["q_star"],
            out["q"],
            out["fibre"],
            out["residue_classes"],
            out["covered"],
            f"{coverage:.15f}",
            out["max_credit"],
            out["best_pair"],
        )

        if mechanical == "1010110110101101101":
            residue, lo, hi = out["best_pair"]
            assert lo == 457643
            assert hi == 2406260
            assert hi - lo == 11 * (3 ** 11)
            assert residue == 103349

    print("credit histograms")
    for mechanical in MACROBLOCKS:
        out = analyze(mechanical)
        print(mechanical, sorted(out["hist"].items()))


if __name__ == "__main__":
    main()
