#!/usr/bin/env python3
"""Exact Stern-Brocot macro grammar for the first-resonance Christoffel word.

The existing anchored Christoffel DAG has 138 distinct nodes.  This certificate
compresses the same ordered Farey construction by grouping consecutive equal
Stern-Brocot moves.  The resulting first-resonance word is generated by only
21 macro runs, followed by the final mediant concatenation.

No full 72-billion-letter word is materialized.
"""

P = 42_150_895_613
Q = 72_057_431_991

EXPECTED_RUNS = [
    ('R',1),('L',2),('R',2),('L',3),('R',1),('L',5),('R',2),('L',23),
    ('R',2),('L',2),('R',1),('L',1),('R',55),('L',1),('R',4),('L',3),
    ('R',1),('L',1),('R',15),('L',1),('R',9),
]


def append_run(runs, ch):
    if runs and runs[-1][0] == ch:
        runs[-1] = (ch, runs[-1][1] + 1)
    else:
        runs.append((ch, 1))


def main() -> None:
    # Farey bounds and their anchored word statistics (ones,length).
    L = (0,1)
    R = (1,1)
    runs=[]
    single_moves=0

    while True:
        M=(L[0]+R[0], L[1]+R[1])
        cmp=P*M[1]-M[0]*Q
        if cmp == 0:
            break
        if cmp > 0:
            # target is to the right: L <- mediant, W_L <- W_L W_R
            L=M
            append_run(runs,'R')
        else:
            # target is to the left: R <- mediant, W_R <- W_L W_R
            R=M
            append_run(runs,'L')
        single_moves += 1

    assert (L[0]+R[0], L[1]+R[1]) == (P,Q)
    assert single_moves == 135
    assert runs == EXPECTED_RUNS
    assert len(runs) == 21
    assert max(n for _,n in runs) == 55

    # Macro replay on word statistics.  Repeated R^a sends
    #   W_L -> W_L W_R^a,
    # while L^a sends
    #   W_R -> W_L^a W_R.
    WL=(0,1)
    WR=(1,1)
    for ch,a in runs:
        if ch == 'R':
            WL=(WL[0]+a*WR[0], WL[1]+a*WR[1])
        else:
            WR=(a*WL[0]+WR[0], a*WL[1]+WR[1])

    root=(WL[0]+WR[0],WL[1]+WR[1])
    assert root==(P,Q)

    # Euclidean continued-fraction checksum.  The unrolled subtraction count
    # is the sum of partial quotients minus the endpoint adjustment.
    p,q=P,Q
    euclid=[]
    while p:
        a=q//p
        euclid.append(a)
        q,p=p,q-a*p
    assert sum(euclid) == 137
    assert len(euclid) == 22

    print("PASS first-resonance Stern-Brocot macro grammar")
    print("single_mediant_moves",single_moves)
    print("macro_runs",len(runs))
    print("max_macro_repeat",max(n for _,n in runs))
    print("runs",runs)
    print("root_ones",root[0])
    print("root_length",root[1])
    print("euclid_partial_quotients",euclid)


if __name__ == '__main__':
    main()
