#include <algorithm>
#include <cassert>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

// Exact same-integer intersection for the unresolved m=45 first-defect p=10
// channel at depth 28.
//
// Inputs q18.bin,...,q25.bin are generated by the existing exact builder
//
//   depth28_hensel_retained_residue_qslice.cpp
//
// and contain sorted retained canonical N residues modulo 2^28.  This file:
//
//  1. selects exactly those retained residues whose first difference from the
//     current mechanical word is the p=10 flip;
//  2. converts N=4Y+3 to the reduced Y residue modulo 2^26;
//  3. intersects that dyadic hard set with each of the two m=45 ternary
//     affine blocks using an exact cyclic NTT correlation;
//  4. independently recomputes the raw p=10 selector count modulo 2^9.
//
// The result is an exact finite reduction, not a closure of the p=10 channel
// and not a proof of the Collatz conjecture.

using u32 = std::uint32_t;
using u64 = std::uint64_t;

namespace {

constexpr u32 MOD_NTT = 2'013'265'921U;   // 15*2^27 + 1
constexpr u32 ROOT = 31U;
constexpr u32 N = 1U << 26;               // Y modulus for N mod 2^28
constexpr u32 MASK = N - 1;
constexpr u32 MECH_N28 = 163'470'331U;
constexpr u32 P10_DELTA = 1U << 10;
constexpr u32 LOW11_MASK = (1U << 11) - 1;
constexpr u32 TARGET_N11 =
    (MECH_N28 + P10_DELTA) & LOW11_MASK;   // 2043
constexpr u32 TARGET_Y9 = (TARGET_N11 - 3U) >> 2; // 510

u32 modpow(u32 a, u64 e) {
    u64 r = 1;
    u64 b = a;
    while (e) {
        if (e & 1) r = r * b % MOD_NTT;
        b = b * b % MOD_NTT;
        e >>= 1;
    }
    return static_cast<u32>(r);
}

void ntt(std::vector<u32>& a, bool inverse) {
    const std::size_t n = a.size();
    for (std::size_t i = 1, j = 0; i < n; ++i) {
        std::size_t bit = n >> 1;
        for (; j & bit; bit >>= 1) j ^= bit;
        j ^= bit;
        if (i < j) std::swap(a[i], a[j]);
    }

    for (std::size_t len = 2; len <= n; len <<= 1) {
        u32 wlen = modpow(ROOT, (MOD_NTT - 1) / len);
        if (inverse) wlen = modpow(wlen, MOD_NTT - 2);
        const std::size_t half = len >> 1;
        for (std::size_t i = 0; i < n; i += len) {
            u64 w = 1;
            for (std::size_t j = 0; j < half; ++j) {
                const u32 u = a[i + j];
                const u32 v = static_cast<u32>(w * a[i + j + half] % MOD_NTT);
                u32 s = u + v;
                if (s >= MOD_NTT) s -= MOD_NTT;
                a[i + j] = s;
                a[i + j + half] = (u >= v) ? (u - v) : (u + MOD_NTT - v);
                w = w * wlen % MOD_NTT;
            }
        }
    }

    if (inverse) {
        const u32 invn = modpow(static_cast<u32>(n), MOD_NTT - 2);
        for (u32& x : a) x = static_cast<u32>(u64(x) * invn % MOD_NTT);
    }
}

u32 pow3mod(int e, u32 mask) {
    u32 x = 1;
    for (int i = 0; i < e; ++i) x = static_cast<u32>(u64(x) * 3U) & mask;
    return x;
}

std::vector<u32> subset_sums_mod(int begin, int end, u32 mask) {
    std::vector<u32> out(1, 0);
    out.reserve(std::size_t{1} << (end - begin));
    u32 w = pow3mod(begin, mask);
    for (int i = begin; i < end; ++i) {
        const std::size_t old = out.size();
        out.resize(2 * old);
        for (std::size_t j = 0; j < old; ++j)
            out[old + j] = (out[j] + w) & mask;
        w = static_cast<u32>(u64(w) * 3U) & mask;
    }
    return out;
}

u64 raw_p10_count(bool high44) {
    constexpr u32 M = 1U << 9;
    constexpr u32 MMASK = M - 1;
    std::vector<u64> dp(M, 0), next(M, 0);

    u32 base = pow3mod(45, MMASK);
    if (high44) base = (base + pow3mod(44, MMASK)) & MMASK;
    dp[base] = 1;

    u32 w = 1;
    for (int i = 0; i < 44; ++i) {
        next = dp;
        for (u32 r = 0; r < M; ++r)
            next[(r + w) & MMASK] += dp[r];
        dp.swap(next);
        w = static_cast<u32>(u64(w) * 3U) & MMASK;
    }
    return dp[TARGET_Y9];
}

} // namespace

int main(int argc, char** argv) {
    const std::string dir = (argc >= 2 ? argv[1] : ".");

    std::vector<u32> allow(N, 0);
    const int expected_by_q[8] = {1397, 4572, 3467, 1647, 542, 120, 17, 1};
    u64 allowed_count = 0;

    for (int q = 18; q <= 25; ++q) {
        const std::string path = dir + "/q" + std::to_string(q) + ".bin";
        std::ifstream f(path, std::ios::binary | std::ios::ate);
        if (!f) {
            std::cerr << "cannot open " << path << "\n";
            return 1;
        }
        const std::streamsize bytes = f.tellg();
        f.seekg(0);
        if (bytes % 4) return 2;
        std::vector<u32> residues(static_cast<std::size_t>(bytes / 4));
        f.read(reinterpret_cast<char*>(residues.data()), bytes);
        if (!f) return 3;

        int count_q = 0;
        for (const u32 x : residues) {
            if (((x - MECH_N28) & LOW11_MASK) != P10_DELTA) continue;
            assert((x & 3U) == 3U);
            const u32 y = (x - 3U) >> 2;
            if (allow[y]) return 4;
            allow[y] = 1;
            ++count_q;
            ++allowed_count;
        }
        if (count_q != expected_by_q[q - 18]) return 5;
    }

    if (allowed_count != 11'763ULL) return 6;

    // Low 21 selectors are transformed as a cyclic multiplicity polynomial.
    std::vector<u32> low_reverse(N, 0);
    const auto low = subset_sums_mod(0, 21, MASK);
    for (const u32 x : low) ++low_reverse[(-x) & MASK];

    ntt(low_reverse, false);
    ntt(allow, false);
    for (u32 i = 0; i < N; ++i)
        low_reverse[i] = static_cast<u32>(u64(low_reverse[i]) * allow[i] % MOD_NTT);
    ntt(low_reverse, true);

    // High 23 selectors are enumerated exactly.  The convolution coefficient
    // is at most 2^21, so the single NTT prime cannot wrap the integer count.
    const auto high = subset_sums_mod(21, 44, MASK);
    const u32 p45 = pow3mod(45, MASK);
    const u32 p44 = pow3mod(44, MASK);

    u64 hard[2] = {0, 0};
    u64 nonzero_high[2] = {0, 0};
    u32 max_low_per_high[2] = {0, 0};

    for (const u32 h : high) {
        for (int block = 0; block < 2; ++block) {
            const u32 shift = (h + p45 + (block ? p44 : 0U)) & MASK;
            const u32 v = low_reverse[shift];
            hard[block] += v;
            if (v) {
                ++nonzero_high[block];
                max_low_per_high[block] = std::max(max_low_per_high[block], v);
            }
        }
    }

    const u64 raw0 = raw_p10_count(false);
    const u64 raw1 = raw_p10_count(true);

    if (raw0 != 34'359'739'317ULL) return 7;
    if (raw1 != 34'359'721'961ULL) return 8;
    if (hard[0] != 3'083'595'585ULL) return 9;
    if (hard[1] != 3'083'550'671ULL) return 10;
    if (nonzero_high[0] != (1ULL << 23) || nonzero_high[1] != (1ULL << 23)) return 11;
    if (max_low_per_high[0] != 459U || max_low_per_high[1] != 459U) return 12;

    std::cout << "m45 p10 depth28 q-sliced Hensel correlation: PASS\n";
    std::cout << "p10 retained dyadic residues=" << allowed_count << "\n";
    std::cout << "block0 raw=" << raw0 << " hard=" << hard[0] << "\n";
    std::cout << "block1 raw=" << raw1 << " hard=" << hard[1] << "\n";
    std::cout << "nonzero high-selector shifts=" << nonzero_high[0]
              << "," << nonzero_high[1] << "\n";
    std::cout << "max low matches per high shift=" << max_low_per_high[0]
              << "," << max_low_per_high[1] << "\n";
    return 0;
}
