#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <string>
#include <vector>

// Exact depth-28 renewal-syndrome graph certificate for the current m=45 hard
// language.  Inputs q18.bin,...,q28.bin are the disjoint retained canonical-N
// residue slices generated by depth28_hensel_retained_residue_qslice.cpp.
//
// The verifier corrects an earlier exploratory overinterpretation: under one
// fixed normalization rule there is NOT a long 2680->529->125->25->5 chain.
// The exact recursive exceptional graph inside the depth-28 window is only
//
//     E10 (2680) --> E18 (25)
//          |------> E21 (5)
//
// and every finite return from E18 or E21 normalizes back into an ordinary
// later first-defect hard state.  The remaining no-return states simply carry
// positive height through the right boundary of the 28-bit window.
//
// This is a finite-state compression theorem for the current hard language, not
// a Collatz proof.

using u32 = std::uint32_t;
using u64 = std::uint64_t;

namespace {
constexpr int L = 28;
constexpr u32 MOD = 1u << L;
constexpr u32 MASK = MOD - 1;
const std::string H19 = "1101101101011011010";

std::string mechanical() {
    std::string s;
    while (int(s.size()) < L) s += H19;
    s.resize(L);
    return s;
}

std::vector<int> parity(u32 r) {
    u64 x = r;
    std::vector<int> b(L);
    for (int i = 0; i < L; ++i) {
        b[i] = int(x & 1ULL);
        x = b[i] ? (3*x + 1)/2 : x/2;
    }
    return b;
}

u32 canonical(const std::vector<int>& b) {
    u64 r = 0, y = 0, p3 = 1;
    for (int k = 0; k < L; ++k) {
        const int bit = b[k];
        const int carry = bit ^ int(y & 1ULL);
        if (carry) {
            r += u64(1) << k;
            y += p3;
        }
        if (bit) {
            y = (3*y + 1)/2;
            p3 *= 3;
        } else {
            y /= 2;
        }
    }
    return u32(r & MASK);
}

int first_defect(const std::vector<int>& b, const std::string& m) {
    for (int i = 0; i < L; ++i) if (b[i] != m[i]-'0') return i;
    return 99;
}

int first_return(const std::vector<int>& b, const std::string& m, int p) {
    int h = 0;
    for (int i = p; i < L; ++i) {
        h += b[i] - (m[i]-'0');
        if (i > p && h == 0) return i;
    }
    return 99;
}

int next_defect(const std::vector<int>& b, const std::string& m, int after) {
    for (int i = after + 1; i < L; ++i) if (b[i] != m[i]-'0') return i;
    return 99;
}

u32 invodd(u32 a) {
    u32 x = 1;
    for (int i = 0; i < 6; ++i) x *= 2 - a*x;
    return x & MASK;
}

u32 pow3mod(int n) {
    u32 x = 1;
    for (int i = 0; i < n; ++i) x = u32(u64(x)*3U) & MASK;
    return x;
}

u32 immediate_translation(int p, const std::string& m) {
    int q_before = 0;
    for (int i = 0; i < p; ++i) q_before += m[i] == '1';
    return u32(u64(1u << p) * invodd(pow3mod(q_before + 1))) & MASK;
}

std::vector<u32> load_all(const std::string& dir) {
    std::vector<u32> out;
    for (int q = 18; q <= 28; ++q) {
        const std::string path = dir + "/q" + std::to_string(q) + ".bin";
        std::ifstream f(path, std::ios::binary | std::ios::ate);
        if (!f) {
            std::cerr << "cannot open " << path << "\n";
            std::exit(1);
        }
        const std::streamsize bytes = f.tellg();
        if (bytes % 4) std::exit(2);
        f.seekg(0);
        const std::size_t old = out.size();
        out.resize(old + std::size_t(bytes/4));
        f.read(reinterpret_cast<char*>(out.data() + old), bytes);
        if (!f) std::exit(3);
    }
    std::sort(out.begin(), out.end());
    out.erase(std::unique(out.begin(), out.end()), out.end());
    return out;
}

std::set<u32> immediate_mapped(const std::set<u32>& S, int p, int nxt,
                               const std::string& m) {
    std::set<u32> out;
    const u32 d = immediate_translation(p, m);
    for (u32 r : S) {
        const auto b = parity(r);
        if (first_defect(b,m) != p) continue;
        if (first_return(b,m,p) != p+1) continue;
        if (next_defect(b,m,p+1) != nxt) continue;
        out.insert((r-d) & MASK);
    }
    return out;
}

std::set<u32> normalized_group(const std::set<u32>& E, int ret, int nxt,
                               const std::string& m) {
    std::set<u32> out;
    for (u32 r : E) {
        auto b = parity(r);
        const int p = first_defect(b,m);
        if (first_return(b,m,p) != ret) continue;
        if (next_defect(b,m,ret) != nxt) continue;
        for (int i = p; i <= ret; ++i) b[i] = m[i]-'0';
        out.insert(canonical(b));
    }
    return out;
}

std::set<u32> difference(const std::set<u32>& A, const std::set<u32>& B) {
    std::set<u32> out;
    std::set_difference(A.begin(),A.end(),B.begin(),B.end(),
                        std::inserter(out,out.end()));
    return out;
}

struct OpenProfile {
    std::map<int,int> endpoint_height;
    std::map<int,int> maximum_height;
    int count = 0;
};

OpenProfile open_profile(const std::set<u32>& E, const std::string& m) {
    OpenProfile out;
    for (u32 r : E) {
        const auto b = parity(r);
        const int p = first_defect(b,m);
        if (first_return(b,m,p) != 99) continue;
        ++out.count;
        int h = 0, mx = 0;
        for (int i = p; i < L; ++i) {
            h += b[i] - (m[i]-'0');
            mx = std::max(mx,h);
        }
        ++out.endpoint_height[h];
        ++out.maximum_height[mx];
    }
    return out;
}

} // namespace

int main(int argc, char** argv) {
    const std::string dir = argc >= 2 ? argv[1] : ".";
    const std::string m = mechanical();
    const auto all = load_all(dir);
    if (all.size() != 1'976'972ULL) return 4;

    std::map<int,std::set<u32>> S;
    for (u32 r : all) {
        const auto b = parity(r);
        S[first_defect(b,m)].insert(r);
    }

    const std::map<int,std::size_t> expected_sizes{
        {2,1'623'807},{5,286'895},{8,51'825},{10,11'763},
        {13,2'151},{16,404},{18,100},{21,20},{24,5},{27,1},{99,1}
    };
    for (auto [p,n] : expected_sizes)
        if (S[p].size() != n) return 5;

    // Ordinary immediate-return conjugacies.  Only 8->10 and 16->18 have
    // extra Hensel states under this normalization.
    const std::array<std::pair<int,int>,9> ordinary_edges{{
        {2,5},{5,8},{8,10},{10,13},{13,16},{16,18},{18,21},{21,24},{24,27}
    }};

    std::set<u32> E10, E18;
    for (auto [p,nxt] : ordinary_edges) {
        const auto M = immediate_mapped(S[p],p,nxt,m);
        const auto extra = difference(M,S[nxt]);
        if (p == 8) {
            if (M.size()!=14'443 || extra.size()!=2'680) return 6;
            E10 = extra;
        } else if (p == 16) {
            if (M.size()!=125 || extra.size()!=25) return 7;
            E18 = extra;
        } else {
            if (M != S[nxt]) return 8;
        }
    }
    if (E10.size()!=2'680 || E18.size()!=25) return 9;

    // E10 has exactly two finite-return exceptional normalized children.
    const auto G17 = normalized_group(E10,17,18,m);
    const auto X17 = difference(G17,S[18]);
    if (X17 != E18) return 10;

    const auto G20 = normalized_group(E10,20,21,m);
    const auto E21 = difference(G20,S[21]);
    if (E21.size()!=5) return 11;

    // Every other finite-return group from E10 normalizes wholly into the
    // ordinary later hard set.
    const std::map<std::pair<int,int>,int> e10_groups{
        {{14,16},404},{{14,18},100},{{14,21},20},{{14,24},5},{{14,27},1},{{14,99},1},
        {{15,16},404},{{15,18},100},{{15,21},20},{{15,24},5},{{15,27},1},{{15,99},1},
        {{17,18},125},
        {{19,21},40},{{19,24},10},{{19,27},2},{{19,99},2},
        {{20,21},110},{{20,24},15},{{20,27},3},{{20,99},3},
        {{22,24},45},{{22,27},9},{{22,99},9},
        {{23,24},115},{{23,27},9},{{23,99},9},
        {{25,27},42},{{25,99},42},{{26,27},113},{{26,99},50}
    };
    for (auto [key,orig] : e10_groups) {
        const int ret=key.first,nxt=key.second;
        const auto M=normalized_group(E10,ret,nxt,m);
        if (ret==17 && nxt==18) {
            if (difference(M,S[nxt])!=E18) return 12;
        } else if (ret==20 && nxt==21) {
            if (difference(M,S[nxt])!=E21) return 13;
        } else {
            if (difference(M,S[nxt]).size()!=0) return 14;
        }
        // orig is a regression count on source representatives, not mapped size.
        int c=0;
        for(u32 r:E10){auto b=parity(r);int p=first_defect(b,m);
            if(first_return(b,m,p)==ret && next_defect(b,m,ret)==nxt) ++c;}
        if(c!=orig) return 15;
    }

    // E18 and E21 have no exceptional finite-return descendants.
    const std::array<std::pair<int,int>,9> e18_groups{{
        {22,24},{22,27},{22,99},{23,24},{23,27},{23,99},{25,27},{25,99},{26,27}
    }};
    for (auto [ret,nxt] : e18_groups)
        if (!difference(normalized_group(E18,ret,nxt,m),S[nxt]).empty()) return 16;

    const std::array<std::pair<int,int>,4> e21_groups{{
        {25,27},{25,99},{26,27},{26,99}
    }};
    for (auto [ret,nxt] : e21_groups)
        if (!difference(normalized_group(E21,ret,nxt,m),S[nxt]).empty()) return 17;

    // Open excursions at the depth-28 boundary.
    const auto O10=open_profile(E10,m), O18=open_profile(E18,m), O21=open_profile(E21,m);
    if (O10.count!=865 || O18.count!=7 || O21.count!=1) return 18;
    if (O10.endpoint_height != std::map<int,int>{{1,218},{2,367},{3,203},{4,65},{5,12}}) return 19;
    if (O10.maximum_height != std::map<int,int>{{2,194},{3,419},{4,214},{5,35},{6,3}}) return 20;
    if (O18.endpoint_height != std::map<int,int>{{1,3},{2,4}}) return 21;
    if (O18.maximum_height != std::map<int,int>{{2,4},{3,3}}) return 22;
    if (O21.endpoint_height != std::map<int,int>{{1,1}}) return 23;
    if (O21.maximum_height != std::map<int,int>{{2,1}}) return 24;

    std::cout << "m45 depth28 renewal syndrome graph: PASS\n";
    std::cout << "ordinary hard sizes p2,p5,p8,p10 "
              << S[2].size() << " " << S[5].size() << " "
              << S[8].size() << " " << S[10].size() << "\n";
    std::cout << "exception states E10=" << E10.size()
              << " E18=" << E18.size() << " E21=" << E21.size() << "\n";
    std::cout << "recursive exceptional edges E10->E18, E10->E21 only\n";
    std::cout << "open boundary states " << O10.count << " "
              << O18.count << " " << O21.count << "\n";
    return 0;
}
