// Exact finite scan for first coefficient crossings with x < 2 q^2.
//
// For every start 1 <= x <= 2*QMAX^2, compute its first coefficient
// contraction under the accelerated one-division map
//   T(n)=n/2 (even), (3n+1)/2 (odd).
// If the odd count at first contraction is q <= QMAX and x < 2 q^2,
// retain the minimum observed defect count for that q.
//
// kappa_i=floor(i log_2 3) and coefficient thresholds are generated by
// exact big-integer comparisons. uint64 trajectory arithmetic is guarded
// against overflow; the certified QMAX=50000 run reports zero overflows.
//
// This is a finite computational verifier, not an asymptotic theorem.

#include <boost/multiprecision/cpp_int.hpp>
#include <cstdint>
#include <iostream>
#include <limits>
#include <string>
#include <vector>

using boost::multiprecision::cpp_int;

int main(int argc, char** argv) {
    int QMAX = argc > 1 ? std::stoi(argv[1]) : 50000;
    uint64_t XMAX = 2ULL * static_cast<uint64_t>(QMAX) * static_cast<uint64_t>(QMAX);

    std::vector<int> kappa(QMAX + 2);
    cpp_int p3 = 1;
    for (int i = 0; i <= QMAX + 1; ++i) {
        if (i > 0) p3 *= 3;
        kappa[i] = static_cast<int>(boost::multiprecision::msb(p3));
    }

    const int KMAX = kappa[QMAX] + 2;
    std::vector<int> threshold(KMAX + 2);
    int qthr = 0;
    p3 = 1;
    cpp_int p2 = 1;
    for (int k = 1; k <= KMAX + 1; ++k) {
        p2 <<= 1;
        while (p3 < p2) {
            p3 *= 3;
            ++qthr;
        }
        threshold[k] = qthr;
    }

    const int INF = 1000000000;
    std::vector<int> min_def(QMAX + 1, INF);
    std::vector<uint64_t> min_x(QMAX + 1, 0);
    uint64_t overflow_count = 0;

    for (uint64_t x = 1; x <= XMAX; ++x) {
        uint64_t y = x;
        int q = 0;
        int defects = 0;

        for (int k = 1; k <= KMAX; ++k) {
            if (y & 1ULL) {
                const int i = q;
                const int d = k - 1;
                if (d < kappa[i]) ++defects;
                ++q;

                if (y > (std::numeric_limits<uint64_t>::max() - 1) / 3) {
                    ++overflow_count;
                    break;
                }
                y = (3 * y + 1) / 2;
            } else {
                y /= 2;
            }

            if (q < threshold[k]) {
                if (q <= QMAX && x < 2ULL * static_cast<uint64_t>(q) * static_cast<uint64_t>(q)) {
                    if (defects < min_def[q] ||
                        (defects == min_def[q] && (min_x[q] == 0 || x < min_x[q]))) {
                        min_def[q] = defects;
                        min_x[q] = x;
                    }
                }
                break;
            }
        }
    }

    std::cout << "QMAX " << QMAX << " XMAX " << XMAX
              << " overflow " << overflow_count << "\n";

    int max_hit_q = 0;
    int hit_layers = 0;
    for (int q = 1; q <= QMAX; ++q) {
        if (min_def[q] == INF) continue;
        ++hit_layers;
        max_hit_q = q;
        std::cout << q << " " << min_def[q] << " " << min_x[q] << "\n";
    }

    std::cout << "hit_layers " << hit_layers << "\n";
    std::cout << "max_hit_q " << max_hit_q << "\n";

    return overflow_count == 0 ? 0 : 2;
}
